### ISSUE TITLE
Credentials Provider: Redirect false option response

### ISSUE THREAD

**Issue by junwen-k** [nowaythatworked/auth-astro#10]
Greetings,

Thank you for writing up this great package.
Currently, I am using this package to handle user auth using email and password implementation (Credentials provider), with the redirect option set to `false`.

I've setup my config like this:

`auth-astro.d.ts`
```ts
import NextAuth, { DefaultSession } from '@auth/core';
import { JWT } from '@auth/core/jwt';

declare module '@auth/core/types' {
  interface Session {
    accessToken: string;
  }
  interface User {
    accessToken: string;
  }
}

declare module '@auth/core/jwt' {
  interface JWT {
    accessToken: string;
  }
}

```

`pages/api/auth/[...astroAuth].ts`
```ts
import Credentials from '@auth/core/providers/credentials';
import { AstroAuth, type AstroAuthConfig } from 'auth-astro';

import { logIn } from '../../../apis';

// Issue with `cookie` package with `pnpm`.
// https://github.com/nowaythatworked/auth-astro/issues/9
export const authOpts: AstroAuthConfig = {
  providers: [
    Credentials({
      name: 'Credentials',
      credentials: {
        email: {
          label: 'Email',
          type: 'text',
          placeholder: 'example@email.com',
        },
        password: { label: 'Password', type: 'password' },
      },
      async authorize(credentials) {
        const { success, message, token, user } = await logIn(
          credentials.email as string,
          credentials.password as string,
        );
        if (!success) {
          throw new Error(message); // I expect this to be propagated to the UI, but it did not.
        }
        return { ...user, accessToken: token };
      },
    }),
  ],
  callbacks: {
    async jwt({ token, user }) {
      // We forward the access token retrieve from API to the JWT token.
      if (user) {
        token.accessToken = user.accessToken;
      }
      return token;
    },
    async session({ session, token }) {
      // We forward the access token to the client.
      session.accessToken = token.accessToken;
      return session;
    },
  },
  secret: import.meta.env.SECRET,
};

export const { get, post } = AstroAuth(authOpts);
```

In my client code, I have a simple login button to test the feature.

`index.astro`
```astro
<button id="login">Login Now!</button>

<script>
  const { signIn } = await import('auth-astro/client');
  document.getElementById('login')?.addEventListener('click', async () => {
    const resp = await signIn('credentials', {
      redirect: false,
      email: 'email@example.com',
      password: 'MyPassword',
    });
    console.log(resp); // I expect this to follow the shape based on the documentation https://next-auth.js.org/getting-started/client#using-the-redirect-false-option, to handle errors like incorrect password and etc.
  });
</script>
```

It seems like the response is not according to the documentation. As a side note, I am also getting typescript error:

```sh
Argument of type '{ redirect: boolean; email: string; password: string; }' is not assignable to parameter of type 'AstroSignInOptions'.
  Object literal may only specify known properties, and 'redirect' does not exist in type 'AstroSignInOptions'.ts(2345)
```

Thank you.

**Comment by junwen-k** [comment]
Apparently, the typescript compiler error is coming from 


![image](https://user-images.githubusercontent.com/40173716/225246601-ec5333db-7438-469c-9525-9dd609932b94.png)
```
Cannot find module 'next-auth/react' or its corresponding type declarations.ts(2307)
```

Could this be due to `pnpm` as well? Not sure if it is related to #9.

I've temporary resolved this by running:

```sh
$ pnpm add next-auth -D
```

I think it should be installed by default when installing this package.

**Comment by nowaythatworked** [comment]
> #9

I never used pnpm before. Did something similar happen to you before in a different package? Did you
next-auth is listed as a devDependency in the project. This should be enough because we only import types from it. So it´s really weird that it´s not installing in your system.

**Comment by nowaythatworked** [comment]
Ok, we actually had our dependencies wrong. Putting it as devDependency was not enough and an error on our side. We still only import types so treeshaking should remove all unnecessary files when you build.

For the original issue about the unexptected response I need to do some more digging. 
You´re saying the response is different from the documentation. Did you make sure that the version of the docs is the same as installed? Could you also please give more information on what the actual response is and what you´re expecting?

Thanks for bringing this to our attention.

**Comment by junwen-k** [comment]
@nowaythatworked Thank you for your reply. First time `next-auth` user here and I've been playing around with the configuration.

Apparently, my issue might be related to https://github.com/nextauthjs/next-auth/issues/6512 and it seems like `next-auth` team did hi-jack the error on purpose. One way to test this is to create both projects with minimal setup and compare the response with `auth-astro` and `next-auth`.

According to the documentation [here](https://next-auth.js.org/getting-started/client#using-the-redirect-false-option), the `signIn` method should return a Promise if redirect is set to `false`. This could be changed as I could not find this documentation in authjs.dev website. 🤔 

Currently, I am handling error by using the response `error` query string. E.g,

`utils/error.ts`

```ts
// Based on specification:
// https://next-auth.js.org/configuration/pages#sign-in-page
export type SignInPageError =
  | 'OAuthSignin'
  | 'OAuthCallback'
  | 'OAuthCreateAccount'
  | 'EmailCreateAccount'
  | 'Callback'
  | 'OAuthAccountNotLinked'
  | 'EmailSignin'
  | 'CredentialsSignin'
  | 'SessionRequired'
  | 'Default';

export const getSignInPageError = (url: string) => {
  const searchParams = new URL(url).searchParams;
  const error = searchParams.get('error') as SignInPageError;
  const provider = searchParams.get('provider');
  return {
    error,
    provider,
  };
};
```

`index.astro`

```astro
<button id="login">Login Now!</button>

<script>
  const { signIn } = await import('auth-astro/client');
  document.getElementById('login')?.addEventListener('click', async () => {
    const resp = await signIn('credentials', {
      redirect: false,
      email: 'email@example.com',
      password: 'MyPassword',
    });
    if (resp) {
      const { url } = (await resp?.json()) as { url: string };
      const { error } = getSignInPageError(url);
      if (error === 'CredentialsSignin') {
        // Handle error
      }
    }
  });
</script>
```

Of course, the best way to test this is by creating two minimal setup project for both `next-auth` and `auth-astro` and comparing the response.

**Comment by nowaythatworked** [comment]
Hi @junwen-k it´s important to know that `next-auth` and `@auth/core` is not the same. `@auth/core` originated from `next-auth` but is not an exact copy. 

We published a new version of `auth-astro` yesterday, with this we also upgraded `@auth/core` to the latest version (0.5.1). Make sure you also upgrade it in your project.

If your error still happens I´m not sure how much we can do here as it looks like the error lies in the core. Our package is just an Astro wrapper. Also you should not forget that `@auth/core` is still in pre-release, meaning it´s not stable yet.
