### ISSUE TITLE
Using pages/api instead of astro plugin

### ISSUE THREAD

**Issue by riyaadh-abrahams** [nowaythatworked/auth-astro#18]
Hi there,

I recently installed this package at version 1.0.5 and set it up using the manual API route approach, similar to NextAuth. However, it seems that the recommended method now is to use the Astro plugin system. 

I was wondering if it is still possible to use the manual API route setup instead of the Astro plugin system? I prefer the manual approach and would like to continue using it if possible.

Thanks!

**Comment by Sowce** [comment]
Simply pass `injectEndpoints: false` to the config inside of astro.config.mjs, it still needs the secret and at least an empty providers array and then have a [...auth].ts file inside of /src/api/auth with

`import { AstroAuth } from "auth-astro/server";
import authConfig from "auth:config";

export const authOpts: AstroAuthConfig = {
    ...authConfig,
    // more things likes callbacks, providers, events
};

export const { get, post } = AstroAuth(authOpts);`

I'm not sure this is how the maintainers of the project intended it but that's how I went about it in my own project and it worked

**Comment by nowaythatworked** [comment]
Thank you @Sowce 
The way you showed is the best solution atm. Tbh we didn´t put much focus on "the old method" but there will be an update to improve this way of integration.
