### ISSUE TITLE
Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by DanavsSite** [nowaythatworked/auth-astro#29]

**Comment by TheOtterlord** [comment]
can you share some more details? perhaps a repo, or a full error message & auth config?

**Comment by CMFerrer** [comment]
same problem

 error   Cannot read properties of undefined (reading 'name')
  File:
    .../node_modules/auth-astro/src/integration.ts:29:29
  Code:
    28 |       }
      30 |       const edge = ['@astrojs/vercel/edge', '@astrojs/cloudflare'].includes(
      31 |         astroConfig.adapter.name
      32 |       )

**Comment by TheOtterlord** [comment]
@CMFerrer What SSR adapter are you using?

**Comment by CMFerrer** [comment]
my mistake, there was no adapter ty
