### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by jacobofbrooklyn** [nowaythatworked/auth-astro#34]
> > **Note**: If you´re using pnpm you must also install cookie: `pnpm i cookie`

That `´` should be a `’`. Also, pnpm should be `pnpm`.

> > **Note**: If you’re using `pnpm` you must also install cookie: `pnpm i cookie`

Not that big a deal, just thought I'd let you know

**Comment by nowaythatworked** [comment]
Thanks :) I included it in the newest version
