### ISSUE TITLE
Lower case endpoint names are deprecated and will not be supported in Astro 4.0

### ISSUE THREAD

**Issue by cap340** [nowaythatworked/auth-astro#39]
Hi, nice work and thanks for this integration. 
Not really an issue, just to let you know that this alert message appears on new Astro v3 :

`[astro] Lower case endpoint names are deprecated and will not be supported in Astro 4.0. Rename the endpoint get to GET.`

- **server.ts**

(line 111) ~`async get(event: any) {}`~ `async GET(event: any) {}`
(line 114) ~`async post(event: any) {}`~ `async POST(event: any) {}`

- **./src/api/[...auth].ts**

(line 3) ~`export const { get, post } = AstroAuth()`~ `export const { GET, POST } = AstroAuth()`

The message no longer appears after these modifications
Thanks again

**Comment by nowaythatworked** [comment]
Hi, thanks for bringing this to our attention, a new version has just been released. It supports Astro 4 and this warning should be gone.
