### ISSUE TITLE
Should support `output=hybrid` + `prerender=false`?

### ISSUE THREAD

**Issue by Reimirno** [nowaythatworked/auth-astro#69]
Of course the page that uses `getSession` should be SSR. But it seems that `output=hybrid` with `export const prerender=false` on the every page that uses `auth-astro` still leads to the following error (when you login or logout - i.e. when you use auth endpoints):

![image](https://github.com/nowaythatworked/auth-astro/assets/82516689/6e798eba-260a-4099-8255-09925972abcb)

Which I guess I understand why - `auth-astro` need to inject those auth endpoints but in `hybrid` mode then are by default SSG which they shouldn't. Putting `export const prerender=false` on the app pages do not really change anything as they don't affect the endpoint pages - at least that's my understanding.

It is annoying, because the majority of my pages are SSG and only a few pages are SSR and they needs user to login and view. I am doing ok by switching `output=server` and putting `export const prerender=true` to all SSG pages (opt in instead of opt out) but I wonder if there is a better workaround / built-in support.

**Comment by nowaythatworked** [comment]
Hi, thanks for bringing this to my attention.
I´ll include 
```ts
export const prerender = false;
```
with the next patch, like @MiniCheese26 suggested.
