### ISSUE TITLE
get provider source with getSession

### ISSUE THREAD

**Issue by gustipardo** [nowaythatworked/auth-astro#71]
I am using three providers at the same time. The getSession function gives me the user's ID, but it can conflict with the ID of another user in another provider. So, I created a table called users which has a user_id_provider and a user_provider column corresponding to a unique user UUID. When I want to log in and execute methods, I need the UUID. To find the actual UUID, I need the user's provider ID and the user's provider, but getSession only gives me the user's provider ID. Is there any way to get the actual provider session?

**Comment by nowaythatworked** [comment]
Hi,
please follow Auth.js Guides on [User Managment](https://authjs.dev/guides/creating-a-database-adapter#user-management) since this is out of scope for this project.
Thanks :)
