### ISSUE TITLE
Error on cancel login

### ISSUE THREAD

**Issue by javimata** [nowaythatworked/auth-astro#75]
I'm using Google provider, but when i click on cancel login i return to my site but to a inexistent url, this is a video for another site when use twitch provider but with the same error access_denied

https://github.com/midudev/la-velada-web-oficial/assets/2237207/d293ba28-cec5-4b0c-a74f-e12cc82f5ade

**Comment by nowaythatworked** [comment]
Thank you @javimata for bringing this up. I found what caused the error and will release a patch soon.
